# Generated by Django 4.2.15 on 2025-07-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrondissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_nom', models.CharField(choices=[('Ampaneva', 'ampaneva'), ('Manjakandriana', 'manjakandriana'), ("Talatan'ny volon'ondry", "talatan'ny volon'ondry")], max_length=30)),
                ('arrondissement_numero', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04')], max_length=3)),
            ],
        ),
    ]
