# Generated by Django 4.2.15 on 2025-07-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrondissement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrondissement',
            name='arrondissement_numero',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='arrondissement',
            name='district_nom',
            field=models.CharField(max_length=30),
        ),
    ]
