# Generated by Django 4.2.15 on 2025-07-01 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrondissement', '0002_alter_arrondissement_arrondissement_numero_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrondissement',
            old_name='district_nom',
            new_name='arrondissement_nom',
        ),
    ]
