# Generated by Django 4.2.23 on 2025-07-03 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arrondissement', '0003_rename_district_nom_arrondissement_arrondissement_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_responsable', models.CharField(max_length=100)),
                ('prenom_responsable', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('mot_de_passe', models.CharField(max_length=100)),
                ('nouveau_mot_de_passe', models.CharField(blank=True, max_length=100, null=True)),
                ('date_enregistrement', models.DateField(auto_now_add=True)),
                ('responsable_arrondissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrondissement.arrondissement')),
            ],
        ),
    ]
