# Generated by Django 4.2.23 on 2025-07-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsable',
            old_name='responsable_arrondissement',
            new_name='arrondissement',
        ),
    ]
