# Generated by Django 4.2.23 on 2025-07-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsable', '0002_rename_responsable_arrondissement_responsable_arrondissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='image_responsable',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/img/'),
        ),
    ]
