# Generated by Django 4.2.23 on 2025-07-11 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsable', '0003_responsable_image_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsable',
            name='nouveau_mot_de_passe',
        ),
    ]
