# Generated by Django 4.2.23 on 2025-07-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsable', '0004_remove_responsable_nouveau_mot_de_passe'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='fonction',
            field=models.CharField(blank=True, choices=[('district', 'Chef de District'), ('arrondissement', "Chef d'Arrondissement")], max_length=20, null=True),
        ),
    ]
