# Generated by Django 4.2.23 on 2025-07-23 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responsable', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='destinataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responsable.responsable'),
        ),
    ]
