# Generated by Django 4.2.15 on 2025-08-12 12:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('responsable', '0007_alter_notification_destinataire'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('ajout', 'Ajout'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('validation', 'Validation'), ('connexion', 'Connexion'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('date_action', models.DateTimeField(default=django.utils.timezone.now)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsable.responsable')),
            ],
        ),
    ]
