# Generated by Django 4.2.15 on 2025-08-19 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('responsable', '0007_alter_notification_destinataire'),
        ('arrondissement', '0003_rename_district_nom_arrondissement_arrondissement_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_personne', models.CharField(max_length=100)),
                ('prenom_personne', models.CharField(max_length=250)),
                ('date_de_naissance', models.CharField(max_length=50)),
                ('lieu_de_naissance', models.CharField(max_length=200)),
                ('signe_particulier', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_sexe', models.CharField(max_length=1)),
                ('numero_cin', models.CharField(max_length=6)),
                ('est_valide', models.BooleanField(default=False)),
                ('sexe', models.CharField(choices=[('Homme', 'homme'), ('Femme', 'femme')], max_length=10)),
                ('domicile', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('pere', models.CharField(max_length=300)),
                ('mere', models.CharField(max_length=300)),
                ('date_enregistrement_cin', models.CharField(max_length=100)),
                ('lieu_enregistrement_cin', models.CharField(max_length=100)),
                ('nouveau_nom_personne', models.CharField(blank=True, max_length=200, null=True)),
                ('surnoms_personne', models.CharField(blank=True, max_length=150, null=True)),
                ('commune_personne', models.CharField(blank=True, max_length=150, null=True)),
                ('taille_personne', models.CharField(max_length=200)),
                ('origine', models.CharField(max_length=100)),
                ('service_nationale', models.CharField(blank=True, max_length=50, null=True)),
                ('date_remplacement_cni', models.CharField(blank=True, max_length=50, null=True)),
                ('bon_de_commande', models.CharField(max_length=50)),
                ('est_exporte_cni', models.BooleanField(default=False)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_modification', models.DateField(auto_now=True)),
                ('code_district', models.CharField(blank=True, max_length=10)),
                ('code_arrondissement', models.CharField(blank=True, max_length=10)),
                ('type_cin', models.CharField(blank=True, choices=[('Primata', 'primata'), ('Duplicata', 'duplicata')], max_length=10)),
                ('arrondissement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arrondissement.arrondissement')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='responsable.responsable')),
            ],
        ),
    ]
