# Generated by Django 4.2.15 on 2025-09-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0002_alter_personne_type_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
