# Generated by Django 4.2.15 on 2025-09-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0003_personne_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/img/'),
        ),
    ]
